# backend/core/migrations/0002_documentchunk_embedding.py
# Generated by Django 6.1 on 2026-08-20 08:37

import pgvector.django.vector
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        CreateExtension("vector"),

        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=384,
                null=True,
            ),
        ),
    ]