# Generated by Django 6.1 on 2026-09-04 11:50
# backend/core/migrations/0004_backfill_course_owner.py
from django.db import migrations


def assign_existing_courses(apps, schema_editor):
    Course = apps.get_model("core", "Course")
    User = apps.get_model("users", "User")

    owner = User.objects.filter(username="test").first()

    if owner is None:
        return

    Course.objects.filter(created_by__isnull=True).update(
        created_by=owner,
    )


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_course_created_by"),
    ]

    operations = [
        migrations.RunPython(assign_existing_courses, reverse),
    ]