# Generated by Django 6.1 on 2026-09-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='supporting_excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
